// knowledge.js

const knowledgeBase = {
  geografi: [
    "Bumi memiliki total 7 benua.",
    "Gunung Everest adalah gunung tertinggi di dunia.",
    "Samudra Pasifik adalah samudra terluas di dunia.",
    "Nil adalah sungai terpanjang di dunia.",
    "Sahara adalah gurun terbesar di dunia.",
    "Amazon adalah sungai terbesar di dunia berdasarkan debit air.",
    "Himalaya adalah rangkaian pegunungan tertinggi di dunia.",
    "Australia adalah negara yang juga merupakan benua.",
    "Kilimanjaro adalah gunung tertinggi di Afrika.",
    "Benua Antartika merupakan benua terdingin dan tertutup es.",
    "Gurun Atacama adalah gurun terkering di dunia.",
    "Gunung Fuji adalah gunung tertinggi di Jepang.",
    "Kilimanjaro adalah gunung tertinggi di Afrika.",
    "Piramida Giza adalah salah satu dari Tujuh Keajaiban Dunia kuno.",
    "Bentang alam Grand Canyon di Amerika Serikat sangat menakjubkan.",
    "Pulau Borneo adalah pulau terbesar ketiga di dunia.",
    "Benua Eropa memiliki jumlah negara terbanyak di dunia.",
    "Benua Amerika terdiri dari Amerika Utara dan Amerika Selatan.",
    "Pulau Greenland adalah pulau terbesar di dunia.",
    "Sungai Nil adalah sungai terpanjang di dunia.",
    "Benua Afrika adalah benua terbesar kedua di dunia.",
    "Gurun Gobi adalah gurun terbesar di Asia.",
    "Gunung Elbrus adalah gunung tertinggi di Eropa.",
    "Pulau Madagaskar adalah pulau terbesar keempat di dunia.",
    "Gurun Kalahari terletak di Afrika Selatan.",
    "Gunung Kilimanjaro adalah gunung tertinggi di Tanzania.",
    "Benua Australia adalah satu-satunya benua yang berada di bawah khatulistiwa.",
    "Pulau Islandia memiliki banyak gunung es dan mata air panas.",
    "Gunung McKinley adalah gunung tertinggi di Amerika Utara.",
    "Benua Asia adalah benua terbesar di dunia.",
    "Samudra Hindia adalah samudra ketiga terbesar di dunia.",
    "Pulau Jawa adalah pulau terpadat di dunia.",
    "Pulau Kalimantan adalah pulau terbesar ketiga di dunia.",
    "Sungai Amazon adalah sungai terpanjang kedua di dunia.",
    "Pulau Sumatera adalah pulau terbesar keenam di dunia.",
    "Benua Amerika Utara adalah benua terbesar ketiga di dunia.",
    "Pulau Selandia Baru terkenal dengan alamnya yang indah.",
    "Benua Eropa adalah benua terkecil di dunia.",
    "Sungai Mississippi adalah sungai terpanjang kedua di Amerika Serikat.",
    "Gurun Sahara adalah gurun terbesar di dunia.",
    "Pulau Sulawesi adalah pulau terbesar keempat di Indonesia.",
    "Sungai Danube adalah sungai terpanjang di Eropa.",
    "Benua Antartika adalah benua terdingin di dunia.",
    "Gunung Vesuvius adalah gunung berapi aktif di Italia.",
    "Sungai Thames adalah sungai terpanjang di Inggris.",
    "Sungai Volga adalah sungai terpanjang di Eropa.",
    "Benua Amerika Selatan adalah benua terbesar keempat di dunia.",
    "Bentang alam Great Barrier Reef di Australia sangat indah.",
    "Benua Amerika adalah benua terbesar kedua di dunia.",
    "Pulau Sri Lanka terkenal dengan keindahan pantainya.",
    "Pulau Filipina adalah pulau terbesar kedua di Asia Tenggara.",
    "Pulau Irlandia dikenal dengan padang rumput hijau yang luas.",
    "Pulau Kuba adalah pulau terbesar kelima di dunia.",
    "Benua Amerika Utara terdiri dari Amerika Serikat, Kanada, dan Meksiko.",
    "Pulau Britania Raya adalah pulau terbesar kesembilan di dunia.",
    //geologi
    "Geologi adalah ilmu yang mempelajari bumi dan proses yang membentuknya.",
    "Bumi terdiri dari tiga lapisan utama: inti, mantel, dan kerak.",
    "Plat tektonik adalah bagian-bagian kerak bumi yang bergerak.",
    "Gunung berapi adalah bukit yang memiliki saluran magma yang aktif.",
    "Letusan gunung berapi dapat menyebabkan hujan abu dan lahar.",
    "Gunung berapi yang belum pernah meletus disebut gunung berapi tidur.",
    "Patahan adalah retakan di kerak bumi akibat tekanan tectonic.",
    "Gempa bumi terjadi akibat pelepasan energi di dalam bumi.",
    "Tsunami adalah gelombang besar yang disebabkan oleh gempa bumi di dasar laut.",
    "Bentang alam Grand Canyon terbentuk oleh erosi sungai.",
    "Batu sedimen terbentuk dari endapan material organik atau mineral.",
    "Batu beku terbentuk dari pendinginan magma di dalam bumi.",
    "Batu metamorf terbentuk dari batuan yang mengalami perubahan suhu dan tekanan tinggi.",
    "Mineral adalah bahan padat yang terbentuk secara alami dan memiliki struktur kristal.",
    "Inti bumi terdiri dari besi dan nikel yang sangat panas.",
    "Bentuk permukaan bumi terbentuk oleh proses erosi dan sedimentasi.",
    "Akuifer adalah lapisan bawah tanah yang menyimpan air.",
    "Pegunungan terbentuk akibat proses tektonik dan pengangkatan bumi.",
    "Sungai adalah aliran air yang mengalir dari pegunungan ke laut.",
    "Gurun terbentuk akibat curah hujan yang rendah dan penguapan yang tinggi.",
    "Endapan glasial adalah batuan yang terbentuk oleh gletser.",
    "Pengikisan adalah proses abrasi dan erosi yang merubah bentuk permukaan bumi.",
    "Gunung api adalah gunung yang memiliki kawah yang melepaskan asap dan lava.",
    "Gunung berapi tertinggi di dunia adalah Gunung Everest.",
    "Gempa bumi dapat terjadi di darat atau di dasar laut.",
    "Bentang alam Cappadocia di Turki terkenal dengan formasi batu unik.",
    "Pegunungan Rocky di Amerika Utara terbentuk oleh lempeng tektonik.",
    "Gua adalah rongga di dalam batu yang terbentuk oleh proses erosi.",
    "Gunung berapi Stromboli di Italia terkenal dengan letusan berkala.",
    "Bentang alam Bryce Canyon di Amerika Serikat terdiri dari formasi batu berwarna-warni.",
    "Gempa bumi skala besar dapat menyebabkan kerusakan yang parah.",
    "Proses sedimentasi membentuk batuan sedimen.",
    "Gunung berapi Mount St. Helens di Amerika Serikat meletus pada tahun 1980.",
    "Bentang alam Salar de Uyuni di Bolivia adalah gurun garam terbesar di dunia.",
    "Pegunungan Himalaya terletak di Asia dan merupakan rangkaian pegunungan tertinggi di dunia.",
    "Pegunungan Alpen di Eropa merupakan rangkaian pegunungan tertinggi kedua di dunia.",
    "Gunung berapi Mauna Loa di Hawaii adalah gunung berapi terbesar di dunia.",
    "Sungai Amazon di Amerika Selatan adalah sungai terpanjang di dunia.",
    "Pulau Hawaii terbentuk dari aktivitas gunung berapi di dasar laut.",
    "Bentang alam Danau Baikal di Rusia adalah danau terdalam di dunia.",
    "Gunung berapi Kilauea di Hawaii adalah salah satu gunung berapi paling aktif di dunia.",
    "Gunung berapi Mount Fuji di Jepang adalah salah satu simbol negara tersebut.",
    "Bentang alam Valley of Fire di Amerika Serikat terdiri dari batuan merah yang indah.",
    "Pulau Galapagos di Ekuador terkenal dengan keanekaragaman hayati yang unik.",
    "Gurun Namib di Namibia adalah gurun tertua di dunia.",
    "Pegunungan Andes di Amerika Selatan merupakan rangkaian pegunungan terpanjang di dunia.",
    "Sungai Nil di Afrika adalah sungai terpanjang di dunia.",
    "Bentang alam Antelope Canyon di Amerika Serikat terbentuk oleh erosi air.",
    "Gurun Sahara di Afrika adalah gurun terbesar di dunia.",
    "Gurun Gobi di Asia adalah salah satu gurun terluas di dunia.",
    "Bentang alam Great Barrier Reef di Australia adalah terumbu karang terbesar di dunia.",
    "Bentang alam Monument Valley di Amerika Serikat terkenal dengan batuan runcingnya.",
    "Sungai Yangtze di China adalah sungai terpanjang di Asia.",
    "Bentang alam Matterhorn di Swiss dan Italia adalah gunung berbentuk segitiga unik.",
    "Bentang alam Pantai Pasir Merah di Kepulauan Kokas, Papua adalah pantai dengan pasir berwarna merah.",
    "Bentang alam Kepulauan Raja Ampat di Papua terkenal dengan keindahan bawah lautnya.",
  ],
  fisika: [
      // Mekanika
    "Hukum Newton kedua juga dikenal sebagai hukum inersia dan menyatakan bahwa benda akan tetap diam atau bergerak lurus dengan kecepatan konstan jika gaya eksternal yang bekerja pada benda adalah nol.",
    "Momentum sudut adalah kuantitas fisika yang mengukur rotasi suatu benda dan dinyatakan dalam kg m^2/s.",
    "Ketidakkekalan momentum sudut dikenal sebagai hukum kekekalan momentum sudut dan menyatakan bahwa total momentum sudut dalam sistem tetap konstan jika tidak ada torsi eksternal yang bekerja.",
    "Hukum kekekalan energi mekanik menyatakan bahwa total energi mekanik dalam sistem tertutup tetap konstan selama tidak ada gaya non-konservatif yang bekerja.",
    "Gaya gesekan adalah gaya yang menghambat gerakan relatif antara dua permukaan yang bersentuhan dan bertindak searah berlawanan dengan gerakan.",
    "Kecepatan terminal adalah kecepatan maksimum yang dapat dicapai oleh suatu objek yang jatuh karena gaya gravitasi sebanding dengan luas penampang objek dan koefisien drag udara.",
    "Hukum kekekalan momentum linier adalah salah satu hukum dasar mekanika dan menyatakan bahwa total momentum linier dalam sistem yang terisolasi tetap konstan jika tidak ada gaya eksternal yang bekerja.",
    "Hukum kekekalan energi kinetik menyatakan bahwa total energi kinetik dalam sistem tertutup tetap konstan jika tidak ada gaya eksternal yang bekerja.",
    "Periode adalah waktu yang dibutuhkan oleh suatu benda untuk melakukan satu putaran penuh pada orbitnya.",
    "Frekuensi adalah jumlah putaran atau osilasi yang dilakukan oleh suatu benda per satuan waktu.",
    "Hukum Kepler adalah tiga hukum gerak planet yang dirumuskan oleh Johannes Kepler berdasarkan pengamatan terhadap gerak planet oleh Tycho Brahe.",
    "Gaya sentripetal adalah gaya yang menarik suatu benda menuju pusat rotasi atau orbitnya dan menjaga benda tetap dalam lintasan melingkar.",
    "Energi potensial elastis adalah bentuk energi potensial yang dimiliki oleh pegas yang ditekan atau diregangkan.",
    "Hukum pascal menyatakan bahwa tekanan yang diberikan pada suatu fluida dalam wadah tertutup akan merambat dengan sama ke segala arah dan semua titik dalam fluida.",
    "Prinsip Bernoulli menyatakan bahwa tekanan statis dalam fluida berkurang ketika kecepatan fluida meningkat, dan sebaliknya.",
    "Hukum viskositas Newton menyatakan bahwa perbedaan kecepatan antara lapisan fluida sejajar akan menyebabkan gaya gesek viskositas.",
    "Gaya berat adalah gaya gravitasi yang diberikan pada suatu benda oleh bumi atau benda langit lainnya dan dinyatakan dalam newton (N).",
    "Tegangan permukaan adalah fenomena di mana molekul permukaan suatu cairan menunjukkan gaya tarik-menarik yang kuat, menyebabkan permukaan cairan cenderung untuk mengurangi luasnya.",
    "Laju aliran adalah volume fluida yang melewati suatu area tertentu per satuan waktu dan dinyatakan dalam m^3/s.",
    "Hukum Snellius atau hukum pembiasan Snellius juga berlaku untuk refleksi, yang menggambarkan pembiasan gelombang saat melewati batas antara dua medium.",
    "Hukum Coulomb juga berlaku untuk gaya listrik antara dua muatan, di mana gaya sebanding dengan muatan dan berbanding terbalik dengan kuadrat jarak di antara mereka.",
    "Teori relativitas khusus oleh Albert Einstein menyatakan bahwa hukum fisika tetap berlaku dalam sistem yang mengalami gerakan lurus dan konstan relatif terhadap pengamat, dan kecepatan cahaya adalah konstan dalam ruang hampa.",
    "Teori relativitas umum oleh Albert Einstein adalah teori gravitasi yang menyatakan bahwa benda bermassa melengkungkan ruang-waktu di sekitarnya, menyebabkan benda lain terkena gaya gravitasi karena mengikuti lintasan geodesik dalam ruang-waktu melengkung.",
    //global
    "Hukum gravitasi Newton menyatakan bahwa setiap objek menarik objek lain dengan gaya gravitasi.",
    "Rumus hukum gravitasi Newton adalah F = (G * m1 * m2) / r^2, di mana F adalah gaya gravitasi, G adalah konstanta gravitasi universal, m1 dan m2 adalah massa dua objek, dan r adalah jarak di antara mereka.",
    "Hukum pertama termodinamika menyatakan bahwa energi tidak dapat diciptakan atau dihancurkan, hanya dapat berubah bentuk.",
    "Hukum kedua termodinamika menyatakan bahwa entropi alam semakin meningkat dalam sistem tertutup.",
    "Hukum ketiga termodinamika menyatakan bahwa suhu absolut tidak bisa mencapai nol mutlak.",
    "Gaya adalah ukuran dari interaksi antara dua objek, diukur dalam Newton (N).",
    "Hukum Newton pertama menyatakan bahwa objek akan tetap diam atau bergerak lurus dengan kecepatan konstan kecuali ada gaya eksternal yang bekerja padanya.",
    "Hukum Newton kedua menyatakan bahwa gaya total yang bekerja pada objek adalah massa objek dikalikan dengan percepatannya, atau F = m * a.",
    "Hukum Newton ketiga menyatakan bahwa setiap aksi memiliki reaksi yang sama besarnya dan berlawanan arah.",
    "Momentum adalah produk dari massa dan kecepatan suatu objek, diukur dalam kg m/s.",
    "Hukum kekekalan momentum menyatakan bahwa total momentum sistem tetap konstan jika tidak ada gaya eksternal yang bekerja.",
    "Percepatan adalah perubahan kecepatan suatu objek per satuan waktu, diukur dalam m/s^2.",
    "Hukum kekekalan energi menyatakan bahwa total energi dalam sistem tertutup tetap konstan.",
    "Hukum Coulomb menyatakan bahwa gaya elektrostatik antara dua muatan listrik sebanding dengan perkalian muatan tersebut dan berbanding terbalik dengan kuadrat jarak di antara mereka.",
    "Rumus untuk gaya elektrostatik adalah F = (k * |q1 * q2|) / r^2, di mana F adalah gaya, k adalah konstanta Coulomb, q1 dan q2 adalah muatan dua objek, dan r adalah jarak di antara mereka.",
    "Tegangan listrik adalah perbedaan potensial antara dua titik dalam rangkaian listrik, diukur dalam volt (V).",
    "Arus listrik adalah aliran muatan listrik dalam rangkaian, diukur dalam ampere (A).",
    "Hambatan listrik adalah penghalang aliran arus dalam rangkaian, diukur dalam ohm (Ω).",
    "Hukum Ohm menyatakan bahwa arus dalam rangkaian sebanding dengan tegangan dan berbanding terbalik dengan hambatan, atau I = V / R.",
    "Hukum Faraday tentang induksi elektromagnetik menyatakan bahwa perubahan medan magnet yang melalui kawat menginduksi arus listrik di dalamnya.",
    "Gaya Lorentz adalah gaya yang bekerja pada benda bermuatan yang bergerak dalam medan magnet.",
    "Hukum Ampere menyatakan bahwa arus listrik menghasilkan medan magnet sekelilingnya.",
    "Spektrum elektromagnetik adalah rentang gelombang elektromagnetik, termasuk gelombang radio, sinar gamma, sinar-X, cahaya tampak, dan banyak lagi.",
    "Cahaya adalah gelombang elektromagnetik yang dapat dilihat oleh manusia.",
    "Indeks bias adalah ukuran seberapa banyak cahaya melengkung saat melewati medium, seperti air atau kaca.",
    "Ruang vakum adalah keadaan di mana tidak ada partikel atau materi.",
    "Kecepatan suara adalah kecepatan perambatan gelombang suara melalui medium.",
    "Gelombang suara adalah gelombang mekanik yang merambat melalui medium.",
    "Fenomena interferensi adalah interferensi gelombang saat dua gelombang bertemu.",
    "Fenomena difraksi adalah pembelokan gelombang saat melewati celah atau rintangan.",
    "Gelombang longitudinal adalah gelombang yang arah getarannya sejalan dengan arah perambatan gelombang.",
    "Gelombang transversal adalah gelombang yang arah getarannya tegak lurus terhadap arah perambatan gelombang.",
    "Frekuensi adalah jumlah siklus gelombang per satuan waktu, diukur dalam hertz (Hz).",
    "Panjang gelombang adalah jarak antara dua puncak gelombang atau dua lembah gelombang.",
    "Gelombang elektromagnetik tidak memerlukan medium untuk merambat.",
    "Hukum Snellius atau hukum pembiasan Snellius menggambarkan pembiasan gelombang saat melewati batas antara dua medium.",
    "Hukum Hooke menyatakan bahwa gaya restoratif dari pegas sebanding dengan perpindahan dari posisi setimbangnya.",
    "Bunyi adalah gelombang longitudinal yang merambat melalui medium, seperti udara.",
    "Resonansi adalah fenomena saat getaran dua benda memiliki frekuensi yang sama.",
    "Hambatan gesek adalah hambatan yang timbul saat dua permukaan bersentuhan.",
    "Usaha adalah produk dari gaya yang bekerja pada benda dan perpindahan benda tersebut.",
    "Daya adalah usaha per satuan waktu, diukur dalam watt (W).",
    "Pegas adalah benda elastis yang dapat mengalami deformasi dan kembali ke bentuk semula.",
    "Gelombang gamma adalah radiasi elektromagnetik dengan frekuensi tertinggi dan energi terbesar.",
    "Medan magnet adalah wilayah di sekitar benda bermagnet di mana gaya magnetik dapat dirasakan.",
    "Medan magnet bumi disebut medan magnetik Bumi dan membentuk garis medan dari kutub utara ke kutub selatan.",
    "Gelombang radio adalah radiasi elektromagnetik dengan frekuensi terendah dan energi terendah.",
    "Gelombang mikro adalah gelombang elektromagnetik yang digunakan dalam teknologi komunikasi nirkabel seperti Wi-Fi dan ponsel.",
    "Satuan SI untuk energi adalah joule (J).",
    "Satuan SI untuk daya adalah watt (W).",
    "Satuan SI untuk gaya adalah newton (N).",
    "Satuan SI untuk muatan listrik adalah coulomb (C).",
    "Satuan SI untuk tegangan listrik adalah volt (V).",
  ],
  biologi: [
    "Sel adalah unit dasar struktur dan fungsi kehidupan.",
    "DNA adalah materi genetik yang mengandung informasi genetik dari makhluk hidup.",
    "RNA adalah molekul yang berperan dalam menyampaikan informasi genetik dari DNA dan berperan dalam sintesis protein.",
    "Fotosintesis adalah proses di mana tumbuhan menggunakan cahaya matahari, air, dan karbon dioksida untuk menghasilkan glukosa dan oksigen.",
    "Respirasi sel adalah proses di mana sel mengubah glukosa menjadi energi yang dapat digunakan.",
    "Evolusi adalah perubahan karakteristik genetik suatu populasi dari generasi ke generasi.",
    "Teori sel menyatakan bahwa semua makhluk hidup terdiri dari satu atau lebih sel.",
    "Sel eukariotik memiliki nukleus dan organel sel yang dikelilingi oleh membran.",
    "Sel prokariotik tidak memiliki nukleus dan organel sel yang dikelilingi oleh membran.",
    "Klasifikasi biologis mengelompokkan makhluk hidup berdasarkan kesamaan karakteristik.",
    "Kingdom adalah tingkatan tertinggi dalam taksonomi biologi yang mencakup beberapa filum atau divisio.",
    "Spesies adalah tingkatan terendah dalam taksonomi biologi yang mencakup individu yang dapat saling berinteraksi secara alami dan menghasilkan keturunan yang subur.",
    "Gen adalah segmen DNA yang mengkodekan untuk suatu karakteristik tertentu.",
    "Mutasi adalah perubahan pada urutan DNA yang dapat menyebabkan perubahan dalam karakteristik suatu organisme.",
    "Genetika adalah studi tentang warisan genetik dan variasi genetik di antara makhluk hidup.",
    "Protein adalah molekul besar yang berperan sebagai enzim, sumber energi, dan komponen struktural sel.",
    "Reproduksi adalah proses di mana makhluk hidup menghasilkan keturunan.",
    "Metamorfosis adalah proses perubahan bentuk dari satu bentuk tubuh ke bentuk tubuh lainnya, seperti pada tahap kecoa dari telur menjadi nimfa dan akhirnya dewasa.",
    "Sistem peredaran darah mengangkut oksigen dan nutrisi ke seluruh tubuh.",
    "Sistem pencernaan mencerna makanan menjadi nutrisi yang dapat diserap oleh tubuh.",
    "Sistem pernapasan mengambil oksigen dan mengeluarkan karbon dioksida.",
    "Sistem saraf mengatur dan mengoordinasikan aktivitas tubuh.",
    "Sistem ekskresi mengeluarkan limbah dan zat sisa dari tubuh.",
    "Sistem endokrin mengatur produksi hormon dan mengirimkan pesan kimia ke seluruh tubuh.",
    "Sistem reproduksi menghasilkan sel-sel reproduksi yang dibutuhkan untuk reproduksi.",
    "Sistem kekebalan tubuh melindungi tubuh dari serangan penyakit dan patogen.",
    "Ciri-ciri kehidupan meliputi pertumbuhan, pergerakan, pernapasan, respons terhadap rangsangan, reproduksi, dan memiliki metabolisme.",
    "Perilaku insting adalah perilaku alami yang diwarisi dan terjadi tanpa pembelajaran.",
    "Habitat adalah lingkungan tempat makhluk hidup tinggal dan mencari makanan.",
    "Ekosistem adalah komunitas makhluk hidup yang hidup bersama dengan lingkungan fisiknya.",
    "Lingkungan adalah semua faktor fisik, kimia, dan biologi yang mempengaruhi makhluk hidup.",
    "Ekologi adalah studi tentang hubungan antara makhluk hidup dan lingkungannya.",
    "Hewan herbivora adalah hewan pemakan tumbuhan.",
    "Hewan karnivora adalah hewan pemakan daging.",
    "Hewan omnivora adalah hewan pemakan tumbuhan dan daging.",
    "Hewan ovipar adalah hewan yang berkembang biak dengan bertelur.",
    "Hewan vivipar adalah hewan yang berkembang biak dengan melahirkan.",
    "Tumbuhan autotrof adalah tumbuhan yang dapat membuat makanannya sendiri melalui fotosintesis.",
    "Tumbuhan heterotrof adalah tumbuhan yang tidak dapat membuat makanannya sendiri dan bergantung pada sumber makanan dari luar.",
    "Adaptasi adalah perubahan fisik atau perilaku suatu makhluk hidup untuk bertahan hidup di lingkungan tertentu.",
    "Mimikri adalah bentuk adaptasi di mana makhluk hidup meniru tampilan atau perilaku makhluk hidup lain untuk menghindari pemangsa.",
    "Hibernasi adalah bentuk adaptasi di mana makhluk hidup memasuki periode tidur musim dingin untuk menghemat energi.",
    "Estivasi adalah bentuk adaptasi di mana makhluk hidup memasuki periode tidur musim panas untuk menghindari kondisi kering dan panas.",
    "Kompetisi adalah interaksi antara makhluk hidup yang memperebutkan sumber daya yang terbatas.",
    "Simbiosis adalah interaksi yang menguntungkan antara dua makhluk hidup yang berbeda.",
    "Predasi adalah hubungan antara predator dan mangsanya di mana predator memangsa mangsanya untuk mendapatkan makanan.",
    "Kehutanan adalah studi tentang hutan dan ekosistemnya, termasuk keberlanjutan dan perlindungan hutan.",
    "Biologi molekuler adalah studi tentang struktur dan fungsi molekul biologis, termasuk DNA dan protein.",
  ],
  sejarah: [
    "Kerajaan Sriwijaya adalah salah satu kerajaan maritim terbesar di Nusantara pada abad ke-7 hingga ke-14 Masehi.",
    "Borobudur adalah candi Buddha terbesar di dunia dan merupakan warisan budaya dunia UNESCO.",
    "Kerajaan Majapahit adalah kerajaan terbesar dan paling kuat di Nusantara pada abad ke-14 hingga ke-15 Masehi.",
    "Pangeran Diponegoro memimpin perang melawan Belanda dalam Perang Diponegoro (1825-1830).",
    "Proklamasi Kemerdekaan Indonesia diumumkan oleh Soekarno dan Mohammad Hatta pada 17 Agustus 1945.",
    "Perang Asia Tenggara II (1945-1949) adalah perang kemerdekaan Indonesia melawan penjajahan Belanda.",
    "Konferensi Meja Bundar (KMB) pada tahun 1949 mengakui kedaulatan Republik Indonesia.",
    "Presiden pertama Indonesia adalah Soekarno (1945-1967).",
    "Presiden pertama Republik Indonesia yang dipilih melalui pemilihan umum adalah Soekarno (1955).",
    "Peristiwa G30S/PKI terjadi pada 30 September 1965 dan memicu peristiwa peralihan kekuasaan di Indonesia.",
    "Orde Baru adalah era pemerintahan Presiden Soeharto (1967-1998).",
    "Gerakan 30 September (G30S) adalah upaya kudeta yang gagal oleh kelompok anggota PKI dan militer.",
    "Dewan Konstituante adalah badan legislatif yang bertugas menyusun UUD Indonesia, namun dibubarkan oleh Soekarno pada 5 Juli 1959.",
    "Tragedi Semanggi I terjadi pada 13 November 1998, yang mengakibatkan banyak korban jiwa akibat aksi brutal aparat keamanan terhadap demonstran mahasiswa.",
    "Tragedi Semanggi II terjadi pada 24-25 September 1999 dan menyebabkan banyak korban jiwa dalam bentrokan antara mahasiswa dan aparat keamanan.",
    "Proklamasi Kemerdekaan Papua Barat (Irian Barat) oleh pemerintah Indonesia pada 1 Mei 1963.",
    "Referendum di Papua Barat (Irian Jaya) pada tahun 1969 memutuskan wilayah tersebut tetap menjadi bagian dari Indonesia.",
    "Operasi Seroja adalah invasi Indonesia ke Timor Timur pada tahun 1975.",
    "Timor Timur merdeka sebagai Timor-Leste pada tahun 2002 setelah referendum kemerdekaan.",
    "Aceh mengalami konflik bersenjata yang berkepanjangan antara Gerakan Aceh Merdeka (GAM) dan pemerintah Indonesia.",
    "Pengakuan kedaulatan atas wilayah Irian Jaya dari pemerintah Belanda pada 1963.",
    "Proklamasi kemerdekaan Republik Indonesia Serikat (RIS) pada 27 Desember 1949.",
    "Presiden Indonesia pertama adalah Soekarno yang menjabat dari 1945 hingga 1967.",
    "Presiden Indonesia kedua adalah Soeharto yang menjabat dari 1967 hingga 1998.",
    "Presiden Indonesia ketiga adalah B.J. Habibie yang menjabat dari 1998 hingga 1999.",
    "Presiden Indonesia keempat adalah Abdurrahman Wahid (Gus Dur) yang menjabat dari 1999 hingga 2001.",
    "Presiden Indonesia kelima adalah Megawati Soekarnoputri yang menjabat dari 2001 hingga 2004.",
    "Presiden Indonesia keenam adalah Susilo Bambang Yudhoyono (SBY) yang menjabat dari 2004 hingga 2014.",
    "Presiden Indonesia ketujuh adalah Joko Widodo (Jokowi) yang menjabat sejak 2014 hingga saat ini.",
    "Perang Diponegoro (1825-1830) adalah perang gerilya melawan penjajahan Belanda yang dipimpin oleh Pangeran Diponegoro.",
    "Perang Aceh (1873-1904) adalah perang gerilya melawan penjajahan Belanda di Aceh.",
    "Pertempuran Surabaya terjadi pada 10 November 1945 dan merupakan peristiwa bersejarah dalam sejarah Indonesia.",
    "Konfrontasi Indonesia-Malaysia terjadi antara 1963 dan 1966 akibat masalah perbatasan.",
    "Supersemar adalah surat perintah dari Soeharto yang memberikan wewenang besar kepadanya untuk mengambil alih kekuasaan dari Soekarno pada 11 Maret 1966.",
    "Operasi Jaya Wijaya adalah operasi militer untuk merebut Irian Jaya dari pihak Belanda pada 1962.",
    "Operasi Trikora adalah operasi militer untuk merebut Irian Jaya dari pihak Belanda pada 1961.",
    "Gerakan 30 September (G30S) adalah upaya kudeta yang dilakukan oleh anggota PKI dan militer untuk menggulingkan pemerintahan Soekarno.",
    "Resolusi Jihad adalah kebijakan pemerintah Indonesia untuk membebaskan Palestina dari penjajahan Israel.",
    "Pernyataan Djuanda adalah kebijakan luar negeri Indonesia yang mengutamakan politik luar negeri bebas aktif dan mengutamakan hubungan dengan negara-negara blok ketiga.",
    "Sumpah Pemuda adalah ikrar untuk bersatu dalam satu bahasa, satu tanah air, dan satu bangsa oleh pemuda-pemuda Indonesia pada 28 Oktober 1928.",
    "Perjanjian Roem-Roijen adalah perjanjian antara pemerintah Indonesia dan pemerintah Belanda pada 7 Mei 1949 yang mengakui kedaulatan Indonesia.",
    "Konstitusi RIS adalah konstitusi Indonesia pada masa Republik Indonesia Serikat (RIS).",
    "Operasi Koteka adalah operasi militer untuk merebut Irian Jaya dari pihak Belanda pada 1961.",
    "Operasi Trikora adalah operasi militer untuk merebut Irian Jaya dari pihak Belanda pada 1961.",
    "Perang Banjar adalah perang antara kerajaan-kerajaan Banjar dengan pemerintah kolonial Belanda.",
    "Perang Jawa adalah perang antara pemerintah kolonial Belanda dengan kerajaan-kerajaan di Jawa.",
    "Perang Bali adalah perang antara pemerintah kolonial Belanda dengan kerajaan-kerajaan di Bali.",
    "Perang Makassar adalah perang antara pemerintah kolonial Belanda dengan kerajaan-kerajaan di Sulawesi.",
    "Perang Lombok adalah perang antara pemerintah kolonial Belanda dengan kerajaan-kerajaan di Lombok.",
    "Peradaban Mesir Kuno adalah salah satu peradaban tertua di dunia yang berkembang di sepanjang Sungai Nil.",
    "Kerajaan Romawi adalah salah satu peradaban terbesar dalam sejarah dunia yang berpusat di kota Roma, Italia.",
    "Perang Dunia I terjadi dari tahun 1914 hingga 1918 dan melibatkan banyak negara di dunia.",
    "Perang Dunia II terjadi dari tahun 1939 hingga 1945 dan merupakan konflik terbesar dalam sejarah manusia.",
    "Revolusi Industri dimulai pada abad ke-18 dan mengubah cara produksi dan kehidupan manusia.",
    "Revolusi Prancis terjadi pada tahun 1789 dan menggulingkan monarki di Prancis.",
    "Revolusi Amerika terjadi pada tahun 1775 dan menghasilkan kemerdekaan Amerika Serikat dari Britania Raya.",
    "Kolonialisme Eropa mencapai puncaknya pada abad ke-19 dengan banyaknya negara Eropa yang menjajah wilayah di Asia, Afrika, dan Amerika.",
    "Perjanjian Versailles ditandatangani pada tahun 1919 dan mengakhiri Perang Dunia I.",
    "Perang Dingin adalah konflik antara blok Barat (AS dan sekutunya) dan blok Timur (Uni Soviet dan sekutunya) yang berlangsung selama beberapa dekade setelah Perang Dunia II.",
    "Perang Vietnam adalah konflik antara Vietnam Utara yang komunis dan Vietnam Selatan yang didukung oleh AS.",
    "Amerika Serikat mendeklarasikan kemerdekaannya pada 4 Juli 1776.",
    "Jepang membuka isolasi dirinya pada pertengahan abad ke-19 setelah dikunjungi oleh kapal perang AS.",
    "Kekaisaran Mongol di bawah kepemimpinan Genghis Khan dan cucunya, Kublai Khan, menjadi salah satu imperium terbesar dalam sejarah.",
    "Invasi Normandia pada 6 Juni 1944 (D-Day) adalah pendaratan pasukan Sekutu di Prancis yang menjadi poin balik dalam Perang Dunia II di Eropa.",
    "Abad Pencerahan pada abad ke-17 dan ke-18 adalah periode intelektual dan ilmiah yang penting dalam sejarah Eropa.",
    "Imperium Ottoman adalah salah satu imperium terbesar dalam sejarah dunia yang berpusat di Turki modern.",
    "Bangsa Viking adalah kelompok penjelajah laut dan pedagang dari Skandinavia yang aktif pada abad ke-8 hingga ke-11.",
    "Bangsa Persia (Iran modern) merupakan salah satu peradaban tertua di dunia dan memiliki sejarah yang kaya.",
    "Peradaban Maya adalah peradaban maju yang berkembang di Mesoamerika dan mencapai puncaknya antara abad ke-3 hingga ke-9.",
    "Konstantinopel (sekarang Istanbul) jatuh ke tangan Kesultanan Ottoman pada tahun 1453, yang mengakhiri Kekaisaran Romawi Timur.",
    "Revolusi Industri di Britania Raya membawa perubahan besar dalam produksi dan transportasi.",
    "Perang 100 Tahun adalah konflik antara Inggris dan Prancis yang berlangsung dari 1337 hingga 1453.",
    "Kekaisaran Aztec adalah peradaban besar di Meksiko pra-Kolumbus.",
    "Kekaisaran Inca adalah peradaban besar di Amerika Selatan pra-Kolumbus.",
    "Bangsa Mesir Kuno membangun piramida dan mempraktikkan mumi sebagai bagian dari kepercayaan agama mereka.",
    "Dinasti Han adalah dinasti yang paling berpengaruh dalam sejarah China.",
    "Kerajaan Gupta adalah dinasti penting dalam sejarah India kuno.",
    "Revolusi Rusia pada tahun 1917 menggulingkan pemerintahan Tsar dan membawa komunisme ke Rusia.",
    "Kolonialisasi Amerika dimulai dengan kedatangan bangsa Eropa di Amerika Utara.",
    "Bangsa Sumeria adalah salah satu peradaban tertua di dunia dan berkembang di Mesopotamia.",
    "Bangsa Romawi kuno adalah salah satu peradaban terbesar dan paling berpengaruh di dunia.",
    "Bangsa Yunani kuno adalah salah satu peradaban besar dan berpengaruh dalam sejarah Eropa.",
    "Bangsa Mesir kuno adalah salah satu peradaban tertua di dunia yang berkembang di sepanjang Sungai Nil.",
    "Bangsa Persia kuno adalah salah satu peradaban besar di Timur Tengah.",
    "Kerajaan Mali di Afrika Barat adalah salah satu kerajaan terbesar dan paling makmur di masa lalu.",
    "Kerajaan Aksum adalah peradaban maju di Afrika Timur pada abad ke-1 hingga ke-7.",
    "Kerajaan Khmer adalah salah satu kerajaan terbesar di Asia Tenggara yang dikenal karena candi Angkor Wat.",
    "Revolusi Industri di Inggris pada abad ke-18 mengubah cara produksi dan kehidupan manusia.",
    "Kerajaan Maurya adalah salah satu dinasti penting dalam sejarah India kuno.",
    "Kerajaan Zhou adalah dinasti pertama dalam sejarah Tiongkok.",
    "Kerajaan Qin adalah dinasti yang menyatukan Tiongkok untuk pertama kalinya.",
    "Kerajaan Carolingian di bawah pimpinan Charlemagne adalah salah satu kerajaan terbesar di Eropa pada abad pertengahan.",
    "Perang Salib adalah serangkaian perang agama antara Kristen dan Islam di abad pertengahan.",
    "Perjanjian Tordesillas pada tahun 1494 membagi wilayah dunia antara Spanyol dan Portugal.",
    "Kerajaan Habsburg adalah salah satu dinasti paling berpengaruh dalam sejarah Eropa.",
    "Perang Opium adalah konflik antara Inggris dan China pada abad ke-19 yang berakhir dengan kekalahan China dan penandatanganan Traktat Nanjing.",
    "Perang Seratus Tahun adalah perang antara Inggris dan Prancis yang berlangsung dari 1337 hingga 1453.",
    "Kekaisaran Persia Akhemeniyah adalah salah satu imperium terbesar dalam sejarah dunia yang berpusat di Iran.",
    "Perang Punic adalah serangkaian perang antara Romawi dan Kartago pada abad ke-3 hingga ke-2 SM.",
  ],
  matematika: [
    "Pi (π) adalah suatu konstanta matematika yang nilainya mendekati 3.14.",
    "Rumus Pythagoras digunakan untuk menghitung panjang sisi miring dalam segitiga siku-siku.",
    "Persamaan kuadrat adalah persamaan matematika yang memiliki bentuk ax^2 + bx + c = 0.",
    "Fibonacci sequence adalah deret angka yang setiap angkanya merupakan jumlah dari dua angka sebelumnya (dimulai dari 0 dan 1).",
    "Bilangan prima adalah bilangan yang hanya dapat dibagi oleh 1 dan dirinya sendiri.",
    "Bilangan asli adalah himpunan bilangan positif yang dimulai dari 1.",
    "Logaritma adalah operasi matematika yang berfungsi untuk membalikkan eksponensial.",
    "Integral adalah konsep dalam kalkulus yang digunakan untuk menghitung luas di bawah kurva fungsi.",
    "Turunan adalah konsep dalam kalkulus yang digunakan untuk menghitung tingkat perubahan suatu fungsi.",
    "Trigonometri adalah cabang matematika yang mempelajari hubungan antara panjang sisi dan sudut dalam segitiga.",
    "Faktorial suatu bilangan (n!) adalah hasil perkalian semua bilangan bulat positif dari 1 hingga n.",
    "Teorema Pythagoras menyatakan bahwa dalam segitiga siku-siku, kuadrat panjang sisi miring sama dengan jumlah kuadrat panjang sisi tegak lurus.",
    "Bilangan kompleks adalah bilangan yang terdiri dari bagian nyata dan bagian imajiner (dinyatakan dengan i).",
    "Teorema Garis Singgung menyatakan bahwa garis singgung suatu lingkaran hanya memiliki satu titik kontak dengan lingkaran.",
    "Aljabar adalah cabang matematika yang menggunakan huruf-huruf atau simbol-simbol untuk mewakili nilai yang tidak diketahui.",
    "Notasi sigma (Σ) digunakan untuk menyatakan jumlah dari suatu deret angka.",
    "Rumus luas lingkaran adalah πr^2, di mana r adalah jari-jari lingkaran.",
    "Rumus volume kubus adalah s^3, di mana s adalah panjang sisi kubus.",
    "Persamaan linear adalah persamaan matematika yang hanya memiliki satu variabel dengan pangkat tertinggi 1.",
    "Bangun ruang adalah bentuk tiga dimensi seperti kubus, bola, prisma, dan lain-lain.",
    "Algoritma Euclidean adalah metode untuk mencari FPB (Faktor Persekutuan Terbesar) dari dua bilangan.",
    "Fungsi kuadrat memiliki bentuk umum ax^2 + bx + c, di mana a, b, dan c adalah konstanta.",
    "Persamaan eksponensial adalah persamaan matematika dengan bentuk a^x = b, di mana a dan b adalah konstanta.",
    "Sudut komplemen adalah sepasang sudut yang jika dijumlahkan akan menghasilkan sudut siku-siku (90 derajat).",
    "Grafik adalah representasi visual dari hubungan antara dua atau lebih variabel dalam bentuk koordinat.",
    "Teorema Fermat menyatakan bahwa tidak ada tiga bilangan bulat positif x, y, dan z yang memenuhi persamaan x^n + y^n = z^n untuk n > 2.",
    "Persamaan lingkaran adalah persamaan matematika dengan bentuk (x - h)^2 + (y - k)^2 = r^2, di mana (h, k) adalah pusat lingkaran dan r adalah jari-jarinya.",
    "Himpunan adalah kumpulan objek atau elemen yang memiliki karakteristik yang sama.",
    "Persamaan kuadratik adalah persamaan matematika dengan bentuk ax^2 + bx + c = 0, di mana a ≠ 0.",
    "Diagram Venn adalah representasi visual dari himpunan dan hubungannya.",
    "Bilangan irasional adalah bilangan yang tidak dapat diwakili dalam bentuk pecahan (desimal tak berhingga dan tidak berulang).",
    "Matriks adalah susunan bilangan dalam baris dan kolom yang digunakan untuk melakukan operasi matematika tertentu.",
    "Pitagoras adalah seorang matematikawan kuno yang dikenal karena teoremanya tentang segitiga siku-siku.",
    "Teorema Pythagoras juga berlaku dalam dimensi yang lebih tinggi, seperti dalam segitiga siku-siku tumpul.",
    "Bilangan rasional adalah bilangan yang dapat diwakili dalam bentuk pecahan.",
    "Bilangan bulat adalah himpunan bilangan positif dan negatif beserta angka 0.",
    "Diagram Cartesius adalah representasi visual dari sistem koordinat dua dimensi.",
    "Identitas trigonometri adalah persamaan matematika yang melibatkan fungsi trigonometri dan identik untuk semua nilai sudut.",
    "Grafik fungsi adalah representasi visual dari nilai-nilai fungsi dalam sistem koordinat.",
    "Rumus volume silinder adalah πr^2h, di mana r adalah jari-jari lingkaran alas dan h adalah tinggi silinder.",
    "Matematikawan Yunani Archimedes dikenal karena kontribusinya pada matematika dan ilmu pengetahuan.",
    "Barisan aritmetika adalah deret angka dengan pola pertambahan yang tetap.",
    "Barisan geometri adalah deret angka dengan pola perkalian yang tetap.",
    "Persamaan diferensial adalah persamaan yang melibatkan turunan dari suatu fungsi.",
    "Sudut suplemen adalah sepasang sudut yang jika dijumlahkan akan menghasilkan sudut lurus (180 derajat).",
    "Persamaan eksponensial juga berlaku untuk pertumbuhan eksponensial, seperti dalam populasi bakteri atau investasi keuangan.",
    "Grafik lingkaran adalah representasi visual dari hubungan antara dua variabel dalam bentuk lingkaran.",
    "Teorema Bayes adalah konsep dalam probabilitas yang digunakan untuk menghitung probabilitas suatu peristiwa berdasarkan informasi yang ada.",
    "Rumus volume prisma adalah luas alas dikali tinggi prisma.",
    "Trik kunci perkalian adalah cara mudah mengalikan angka-angka tertentu.",
    "Pangkat bilangan bulat negatif adalah kebalikan dari pangkat bilangan bulat positif.",
    "Grafik parabola adalah representasi visual dari fungsi kuadrat dalam bentuk U atau terbuka.",
    "Hukum asosiatif berlaku untuk operasi matematika tertentu, seperti penjumlahan dan perkalian.",
    "Hukum distributif adalah hukum matematika yang menggabungkan operasi perkalian dan penjumlahan.",
    "Teorema Euclidean tentang bilangan prima menyatakan bahwa ada tak terbatas banyaknya bilangan prima.",
  ],
  kimia: [
    "Air (H2O) adalah molekul yang terdiri dari dua atom hidrogen dan satu atom oksigen.",
    "Tabel periodik adalah pengelompokan unsur-unsur kimia berdasarkan sifat dan karakteristik mereka.",
    "Reaksi kimia adalah proses di mana zat-zat berinteraksi dan mengubah komposisinya untuk membentuk zat baru.",
    "Model atom Bohr menyatakan bahwa elektron bergerak dalam orbit energi terdefinisi di sekitar inti atom.",
    "Asam adalah zat yang memiliki pH kurang dari 7 dan dapat menyumbat warna kertas lakmus merah.",
    "Basah adalah zat yang memiliki pH lebih dari 7 dan dapat menyumbat warna kertas lakmus biru.",
    "Bilangan oksidasi adalah bilangan yang menyatakan muatan relatif suatu atom dalam suatu senyawa atau ion.",
    "Garam adalah senyawa kimia yang terbentuk dari reaksi antara asam dan basa.",
    "Reaksi redoks adalah reaksi kimia di mana terjadi transfer elektron dari satu zat ke zat lain.",
    "Karbon adalah unsur kimia yang merupakan komponen utama dari makhluk hidup dan banyak senyawa organik.",
    "Pereaksi adalah zat yang bereaksi dengan zat lain dalam suatu reaksi kimia.",
    "Katalis adalah zat yang mempercepat kecepatan reaksi kimia tanpa dikonsumsi dalam reaksi tersebut.",
    "Zat organik adalah zat yang mengandung karbon dan biasanya berasal dari makhluk hidup.",
    "Zat anorganik adalah zat yang tidak mengandung karbon dan biasanya tidak berasal dari makhluk hidup.",
    "Ion adalah atom atau molekul yang memiliki muatan listrik karena kehilangan atau mendapatkan elektron.",
    "Mol adalah satuan yang digunakan untuk mengukur jumlah zat dalam kimia.",
    "Koefisien reaktan dalam persamaan reaksi kimia menunjukkan jumlah relatif zat-zat yang terlibat dalam reaksi.",
    "Reaksi eksotermik melepaskan panas ke lingkungan, sementara reaksi endotermik menyerap panas.",
    "Hukum kekekalan massa menyatakan bahwa massa tidak dapat diciptakan atau dihancurkan dalam reaksi kimia.",
    "Hukum perbandingan tetap menyatakan bahwa unsur-unsur dalam senyawa selalu berada dalam perbandingan massa yang tetap.",
    "Suhu kamar adalah suhu standar yang digunakan dalam kondisi eksperimen kimia (sekitar 25 derajat Celsius).",
    "Karbon dioksida (CO2) adalah gas yang dihasilkan oleh manusia dan hewan saat bernapas.",
    "Senyawa polar memiliki muatan listrik yang tidak seimbang di antara atom-atomnya.",
    "Senyawa nonpolar memiliki muatan listrik yang seimbang di antara atom-atomnya.",
    "pH adalah skala yang digunakan untuk mengukur tingkat keasaman atau kebasaan suatu larutan.",
    "Elektrolit adalah zat yang dapat menghantarkan listrik saat larut dalam air.",
    "Isomer adalah senyawa-senyawa yang memiliki rumus molekul yang sama tetapi struktur kimia yang berbeda.",
    "Struktur resonansi adalah representasi alternatif dari molekul yang memiliki keadaan resonansi antara ikatan-ikatannya.",
    "Le Chatelier's principle menyatakan bahwa jika suatu sistem pada kesetimbangan terpengaruh oleh perubahan, ia akan menyesuaikan untuk menentang perubahan tersebut.",
    "Kimia analitik adalah cabang kimia yang berfokus pada analisis komposisi zat.",
    "Kimia organik adalah cabang kimia yang berfokus pada struktur, sifat, dan reaksi senyawa organik.",
    "Kimia fisik adalah cabang kimia yang menggunakan konsep fisika untuk memahami sifat-sifat dan reaksi kimia.",
    "Hukum gas ideal menyatakan bahwa pada kondisi tertentu, gas akan berperilaku secara ideal.",
    "Titik didih adalah suhu di mana zat berubah dari fase cair menjadi fase gas.",
    "Titik lebur adalah suhu di mana zat berubah dari fase padat menjadi fase cair.",
    "Zat aktif adalah bagian dari suatu katalis yang berinteraksi dengan reaktan untuk meningkatkan kecepatan reaksi.",
    "Penghambat adalah zat yang mengurangi kecepatan reaksi dengan menghambat aksi katalis.",
    "Elektrolisis adalah proses di mana listrik digunakan untuk memecah senyawa menjadi unsur-unsur penyusunnya.",
    "Termokimia adalah cabang kimia yang mempelajari perubahan energi selama reaksi kimia.",
    "Sistem tertutup adalah sistem di mana tidak ada pertukaran materi dengan lingkungannya.",
    "Sistem terbuka adalah sistem di mana terjadi pertukaran materi dengan lingkungannya.",
    "Stoikiometri adalah cabang kimia yang mempelajari perbandingan kuantitatif dalam reaksi kimia.",
    "Unsur transuranium adalah unsur kimia yang memiliki nomor atom di atas 92 (uranium).",
    "Kristalisasi adalah proses pembentukan kristal dari suatu larutan jenuh.",
    "Kimia kuantum adalah cabang kimia yang mempelajari perilaku partikel-partikel di tingkat submikroskopik.",
    "Adsorpsi adalah proses penyerapan molekul atau partikel di permukaan suatu benda.",
    "Katalis homogen adalah katalis yang berada dalam fase yang sama dengan reaktan.",
    "Katalis heterogen adalah katalis yang berada dalam fase yang berbeda dengan reaktan.",
  ],
  teknologi: [
    "World Wide Web (WWW) diciptakan oleh Tim Berners-Lee pada tahun 1989.",
    "Perangkat lunak adalah program yang berjalan di komputer dan memberikan instruksi kepada hardware.",
    "Sistem operasi adalah perangkat lunak yang mengelola sumber daya komputer dan memungkinkan aplikasi berjalan.",
    "Pemrograman adalah proses menulis kode komputer untuk menciptakan program atau aplikasi.",
    "Bahasa pemrograman adalah alat yang digunakan untuk berkomunikasi dengan komputer dan menulis kode.",
    "Python adalah bahasa pemrograman yang sering digunakan untuk pengembangan aplikasi web dan ilmu data.",
    "JavaScript adalah bahasa pemrograman yang digunakan untuk mengembangkan aplikasi web interaktif.",
    "Java adalah bahasa pemrograman yang sering digunakan untuk mengembangkan aplikasi lintas platform.",
    "C++ adalah bahasa pemrograman yang sering digunakan untuk pengembangan perangkat lunak dan game.",
    "HTML (HyperText Markup Language) adalah bahasa markah untuk membuat halaman web.",
    "CSS (Cascading Style Sheets) adalah bahasa untuk mengatur tampilan dan format halaman web.",
    "API (Application Programming Interface) adalah antarmuka yang memungkinkan aplikasi berkomunikasi satu sama lain.",
    "Cloud computing adalah model komputasi di mana sumber daya komputer disediakan melalui internet.",
    "Big Data adalah istilah untuk data yang sangat besar dan kompleks yang sulit diolah menggunakan alat tradisional.",
    "Internet of Things (IoT) adalah konsep di mana objek fisik terhubung ke internet dan saling berkomunikasi.",
    "Keamanan siber adalah praktik melindungi sistem komputer dari ancaman dan serangan yang berbahaya.",
    "Blockchain adalah teknologi yang digunakan untuk menyimpan dan memverifikasi transaksi secara terdesentralisasi.",
    "Artificial Intelligence (AI) adalah cabang ilmu komputer yang mengejar penciptaan mesin yang berpikir seperti manusia.",
    "Machine Learning adalah pendekatan dalam AI yang memungkinkan mesin untuk belajar dari data dan meningkatkan kinerjanya.",
    "Virtual Reality (VR) adalah teknologi yang menciptakan pengalaman interaktif dan imersif dalam dunia maya.",
    "Augmented Reality (AR) adalah teknologi yang menggabungkan objek dunia nyata dengan elemen virtual.",
    "Cryptocurrency adalah bentuk uang digital yang menggunakan teknologi kriptografi untuk keamanan transaksi.",
    "Social media adalah platform daring yang memungkinkan pengguna untuk berinteraksi dan berbagi konten.",
    "E-commerce adalah kegiatan berbelanja dan berdagang yang dilakukan secara daring melalui internet.",
    "Search Engine adalah layanan yang memungkinkan pengguna mencari informasi di internet dengan menggunakan kata kunci.",
    "Perangkat keras adalah komponen fisik dari komputer dan perangkat elektronik lainnya.",
    "Perangkat lunak sumber terbuka adalah perangkat lunak yang kode sumbernya dapat diakses oleh publik.",
    "Algoritma adalah langkah-langkah atau aturan untuk menyelesaikan masalah dalam komputasi.",
    "Database adalah kumpulan data yang terstruktur dan diatur untuk memudahkan penyimpanan dan pengambilan data.",
    "Network adalah jaringan yang menghubungkan perangkat dan komputer untuk berbagi data dan sumber daya.",
    "UI (User Interface) adalah antarmuka yang memungkinkan pengguna berinteraksi dengan perangkat atau aplikasi.",
    "UX (User Experience) adalah pengalaman pengguna dalam berinteraksi dengan produk atau layanan.",
    "Scrum adalah metodologi pengembangan perangkat lunak yang berbasis pada prinsip kolaborasi dan adaptasi.",
    "Agile adalah pendekatan pengembangan perangkat lunak yang berfokus pada tanggapan terhadap perubahan.",
    "Sistem kecerdasan bisnis adalah sistem yang membantu organisasi untuk menganalisis data dan mengambil keputusan bisnis.",
    "Server adalah komputer yang menyediakan layanan atau sumber daya bagi komputer lain dalam jaringan.",
    "HTML5 adalah versi terbaru dari bahasa markah HTML dengan dukungan lebih banyak fitur dan fungsionalitas.",
    "CSS3 adalah versi terbaru dari CSS dengan dukungan untuk animasi dan efek tampilan yang lebih canggih.",
    "DNS (Domain Name System) adalah sistem yang mengartikan nama domain menjadi alamat IP komputer.",
    "IPv6 (Internet Protocol version 6) adalah versi terbaru dari protokol internet yang memiliki alamat IP lebih banyak.",
    "Responsive design adalah desain web yang menyesuaikan tampilan dengan perangkat yang digunakan oleh pengguna.",
    "SaaS (Software as a Service) adalah model bisnis perangkat lunak berbasis langganan melalui internet.",
    "PaaS (Platform as a Service) adalah model bisnis yang menyediakan platform untuk mengembangkan aplikasi.",
    "IaaS (Infrastructure as a Service) adalah model bisnis yang menyediakan infrastruktur komputasi secara virtual.",
    "URL (Uniform Resource Locator) adalah alamat unik untuk mengakses sumber daya di internet.",
    "Malware adalah perangkat lunak berbahaya yang dirancang untuk merusak atau mencuri data pengguna.",
    "Firewall adalah perangkat atau perangkat lunak yang melindungi jaringan dari ancaman dan serangan.",
    "SSL (Secure Socket Layer) adalah protokol keamanan yang mengenkripsi data yang dikirimkan melalui internet.",
    "Backup adalah salinan data yang dibuat untuk menghindari kehilangan data dalam kejadian bencana atau kesalahan manusia.",
    "Serverless computing adalah model komputasi di mana penyedia layanan mengelola infrastruktur secara otomatis.",
    "Debugging adalah proses mengidentifikasi dan memperbaiki kesalahan dalam kode program.",
    "Teknologi nirkabel memungkinkan perangkat komunikasi tanpa menggunakan kabel.",
    "Bluetooth adalah teknologi nirkabel yang digunakan untuk mentransfer data antar perangkat dalam jarak dekat.",
    "Wi-Fi adalah teknologi nirkabel yang memungkinkan perangkat terhubung ke internet tanpa kabel.",
    "QR code (Quick Response code) adalah kode matriks dua dimensi yang menyimpan informasi.",
    "GPS (Global Positioning System) adalah sistem navigasi berbasis satelit yang menentukan lokasi geografis.",
    "RFID (Radio-Frequency Identification) adalah teknologi yang menggunakan gelombang radio untuk mengidentifikasi objek.",
    "Drone adalah pesawat tanpa awak yang dikendalikan dari jarak jauh dan digunakan dalam berbagai bidang.",
    "Virtual Assistant adalah program atau aplikasi yang membantu pengguna dengan tugas-tugas tertentu.",
    "Chatbot adalah program komputer yang berinteraksi dengan manusia melalui percakapan.",
    "Cloud storage adalah layanan yang menyimpan data di server eksternal melalui internet.",
    "Streaming adalah layanan yang memungkinkan pengguna menonton atau mendengarkan konten secara daring.",
    "Sosial media adalah platform daring yang memungkinkan pengguna berinteraksi dan berbagi konten.",
    "E-commerce adalah kegiatan berbelanja dan berdagang yang dilakukan secara daring melalui internet.",
    "Cybersecurity adalah praktik melindungi sistem komputer dari ancaman dan serangan yang berbahaya.",
    "Internet of Things (IoT) adalah konsep di mana objek fisik terhubung ke internet dan saling berkomunikasi.",
    "Artificial Intelligence (AI) adalah cabang ilmu komputer yang mengejar penciptaan mesin yang berpikir seperti manusia.",
    "Machine Learning adalah pendekatan dalam AI yang memungkinkan mesin untuk belajar dari data dan meningkatkan kinerjanya.",
    "Virtual Reality (VR) adalah teknologi yang menciptakan pengalaman interaktif dan imersif dalam dunia maya.",
    "Augmented Reality (AR) adalah teknologi yang menggabungkan objek dunia nyata dengan elemen virtual.",
    "Cryptocurrency adalah bentuk uang digital yang menggunakan teknologi kriptografi untuk keamanan transaksi.",
    "Social Engineering adalah teknik manipulasi psikologis untuk memperoleh informasi rahasia dari orang lain.",
    "Biometric adalah metode pengenalan individu berdasarkan ciri fisik atau perilaku unik.",
    "Data mining adalah proses mengeksplorasi data untuk menemukan pola atau hubungan yang berarti.",
    "E-wallet adalah aplikasi yang memungkinkan pembayaran dan transaksi keuangan secara elektronik.",
    "3D printing adalah teknologi mencetak objek tiga dimensi dari berbagai bahan.",
    "Smart Home adalah rumah yang dilengkapi dengan perangkat cerdas untuk otomatisasi dan kontrol.",
    "Smartphone adalah ponsel pintar yang memiliki kemampuan lebih dari sekadar telepon.",
    "Tablet adalah perangkat komputasi berbentuk datar yang lebih besar dari smartphone.",
    "Laptop adalah komputer portabel yang mudah dibawa dan digunakan di mana saja.",
    "SSD (Solid State Drive) adalah perangkat penyimpanan data berbasis flash yang lebih cepat dari hard disk.",
    "Self-driving car adalah mobil yang dapat beroperasi tanpa bantuan pengemudi manusia.",
    "Blockchain adalah teknologi yang digunakan untuk menyimpan dan memverifikasi transaksi secara terdesentralisasi.",
    "Distributed Ledger Technology (DLT) adalah teknologi yang memungkinkan data didistribusikan di banyak lokasi.",
    "Internet Browser adalah aplikasi yang digunakan untuk menjelajahi dan mengakses informasi di internet.",
    "Computer Vision adalah cabang AI yang memungkinkan komputer 'melihat' dan memahami gambar atau video.",
    "Natural Language Processing (NLP) adalah cabang AI yang memungkinkan komputer memahami bahasa manusia.",
    "Cyber-Physical Systems (CPS) adalah sistem yang menggabungkan komponen fisik dan komputer dalam interaksi.",
    "Edge computing adalah model komputasi di mana pemrosesan data dilakukan di sisi jaringan terdekat.",
    "Quantum Computing adalah teknologi komputasi yang berdasarkan pada prinsip mekanika kuantum.",
    "Digital Twin adalah representasi digital dari objek fisik atau proses yang digunakan untuk analisis.",
    "Smart Grid adalah sistem distribusi energi listrik yang menggunakan teknologi informasi dan komunikasi.",
    "Biometric adalah metode pengenalan individu berdasarkan ciri fisik atau perilaku unik.",
    "Computer Vision adalah cabang AI yang memungkinkan komputer 'melihat' dan memahami gambar atau video.",
    "Natural Language Processing (NLP) adalah cabang AI yang memungkinkan komputer memahami bahasa manusia.",
    "Cyber-Physical Systems (CPS) adalah sistem yang menggabungkan komponen fisik dan komputer dalam interaksi.",
    "Edge computing adalah model komputasi di mana pemrosesan data dilakukan di sisi jaringan terdekat.",
    "Quantum Computing adalah teknologi komputasi yang berdasarkan pada prinsip mekanika kuantum.",
    "Digital Twin adalah representasi digital dari objek fisik atau proses yang digunakan untuk analisis.",
    "Smart Grid adalah sistem distribusi energi listrik yang menggunakan teknologi informasi dan komunikasi.",
    "AR/VR in Training adalah penggunaan AR dan VR untuk meningkatkan pelatihan dan simulasi.",
  ],
  ekonomi: [
    "Hukum penawaran dan permintaan adalah dasar dari pasar ekonomi.",
    "PDB (Produk Domestik Bruto) adalah ukuran nilai keseluruhan barang dan jasa yang dihasilkan dalam suatu negara.",
    "Inflasi adalah kenaikan umum harga barang dan jasa selama periode waktu tertentu.",
    "Deflasi adalah penurunan umum harga barang dan jasa selama periode waktu tertentu.",
    "Siklus bisnis mencakup periode ekspansi dan kontraksi dalam aktivitas ekonomi.",
    "Bunga adalah biaya pinjaman uang atau imbalan atas menyimpan uang.",
    "Anggaran adalah rencana pengeluaran dan pendapatan untuk suatu periode tertentu.",
    "Kebijakan moneter adalah tindakan pemerintah terkait pengaturan jumlah uang yang beredar.",
    "Kebijakan fiskal adalah pengaturan pemerintah terkait pengeluaran dan pendapatan untuk mengatur perekonomian.",
    "Investasi adalah pengeluaran untuk membeli barang-barang modal atau aset finansial untuk menghasilkan pendapatan di masa depan.",
    "Bisnis mikro adalah usaha kecil dengan sedikit karyawan dan omset rendah.",
    "Bisnis kecil adalah usaha dengan jumlah karyawan dan omset yang lebih besar dari bisnis mikro.",
    "Bisnis menengah adalah usaha dengan jumlah karyawan dan omset yang lebih besar dari bisnis kecil.",
    "Bisnis besar adalah perusahaan besar dengan banyak karyawan dan omset yang besar.",
    "Outsourcing adalah praktik menggunakan perusahaan eksternal untuk menyediakan barang atau layanan.",
    "Manajemen rantai pasokan adalah proses mengelola aliran barang dan layanan dari awal hingga konsumen akhir.",
    "Nilai tukar adalah harga suatu mata uang dalam satuan mata uang lain.",
    "Kurs adalah harga mata uang asing yang digunakan dalam perdagangan internasional.",
    "Mekanisme pasar adalah cara harga dan kuantitas suatu barang atau jasa ditentukan oleh permintaan dan penawaran.",
    "Kewirausahaan adalah proses memulai dan mengembangkan usaha baru.",
    "Oligopoli adalah pasar dengan sedikit penjual yang mendominasi.",
    "Monopoli adalah pasar dengan satu penjual yang menguasai seluruh pasaran.",
    "Persaingan sempurna adalah pasar dengan banyak penjual dan pembeli tanpa kekuatan pasar.",
    "Bank sentral adalah lembaga yang bertanggung jawab atas pengelolaan mata uang dan kebijakan moneter.",
    "Krisis ekonomi adalah periode penurunan tajam dalam aktivitas ekonomi.",
    "Pasar saham adalah tempat perdagangan saham dan sekuritas lainnya.",
    "Dividen adalah bagian dari laba perusahaan yang dibagikan kepada pemegang saham.",
    "Asuransi adalah perlindungan finansial melalui pembayaran premi untuk risiko tertentu.",
    "Kewajiban adalah hutang atau kewajiban finansial yang harus dibayar oleh perusahaan.",
    "Ekonomi makro adalah studi tentang ekonomi secara keseluruhan termasuk pertumbuhan, inflasi, dan pengangguran.",
    "Ekonomi mikro adalah studi tentang perilaku konsumen dan perusahaan dalam pasar individu.",
    "Penawaran agregat adalah jumlah total barang dan jasa yang ditawarkan di ekonomi.",
    "Permintaan agregat adalah jumlah total barang dan jasa yang diminta oleh konsumen dan perusahaan di ekonomi.",
    "GDP per kapita adalah PDB dibagi dengan jumlah penduduk suatu negara.",
    "Sistem ekonomi kapitalis adalah sistem di mana produksi dan distribusi diatur oleh pasar dan swasta.",
    "Sistem ekonomi sosialis adalah sistem di mana produksi dan distribusi diatur oleh pemerintah.",
    "Sistem ekonomi campuran adalah kombinasi dari sistem kapitalis dan sosialis.",
    "Manajemen adalah proses perencanaan, pengorganisasian, pengarahan, dan pengendalian sumber daya untuk mencapai tujuan tertentu.",
    "Bisnis plan adalah dokumen yang merinci rencana dan strategi bisnis.",
    "Kepemilikan intelektual adalah hak hukum atas kreasi intelektual seperti hak cipta dan paten.",
    "Dampak lingkungan adalah efek dari kegiatan ekonomi dan bisnis terhadap lingkungan.",
    "Risiko bisnis adalah kemungkinan terjadinya kerugian atau ketidakpastian dalam kegiatan bisnis.",
    "Perdagangan internasional adalah pertukaran barang dan jasa antara negara-negara.",
    "Dumping adalah praktik menjual barang di pasar luar negeri dengan harga lebih rendah dari harga di pasar dalam negeri.",
    "Kartel adalah aliansi antara perusahaan untuk mengatur harga dan membatasi persaingan.",
    "Kerjasama antar perusahaan adalah bentuk kemitraan yang melibatkan perusahaan yang berbeda.",
    "Model bisnis adalah kerangka kerja yang menjelaskan cara perusahaan menghasilkan pendapatan.",
    "Layanan keuangan adalah produk dan layanan yang berkaitan dengan keuangan seperti perbankan dan investasi.",
    "Ekonomi kreatif adalah sektor ekonomi yang berkaitan dengan industri kreatif seperti seni, budaya, dan media.",
    "Krisis keuangan adalah periode ketidakstabilan di pasar keuangan.",
    "Bisnis berkelanjutan adalah bisnis yang mempertimbangkan dampak sosial dan lingkungan.",
  ],
  psikologi: [
    "Psikologi adalah ilmu yang mempelajari pikiran, perilaku, dan proses mental manusia.",
    "Sigmund Freud adalah salah satu tokoh terkenal dalam psikologi yang mengembangkan teori psikoanalisis.",
    "Kognitif adalah proses mental yang melibatkan persepsi, pemahaman, dan memori.",
    "Teori belajar klasik oleh Ivan Pavlov melibatkan pembentukan asosiasi antara stimulus dan respons.",
    "Skema adalah struktur kognitif yang membantu mengorganisir dan memahami informasi.",
    "Kondisioning operan oleh B.F. Skinner melibatkan penguatan atau hukuman untuk mengontrol perilaku.",
    "Psikologi perkembangan mempelajari perubahan perilaku dan proses mental seiring pertumbuhan manusia.",
    "Konsep diri adalah persepsi individu tentang diri mereka sendiri.",
    "Efek Hawthorne adalah fenomena di mana individu meningkatkan kinerjanya karena perhatian khusus dari peneliti.",
    "Inteligensi adalah kemampuan untuk belajar, memahami, dan menyelesaikan masalah.",
    "Psikologi sosial mempelajari bagaimana individu dipengaruhi oleh orang lain dan situasi sosial.",
    "Konflik kognitif adalah ketidaksesuaian antara keyakinan atau nilai-nilai seseorang.",
    "Efek halo adalah kecenderungan untuk menilai orang secara keseluruhan berdasarkan kesan awal tentang mereka.",
    "Stres adalah respons fisiologis dan emosional terhadap situasi yang menantang.",
    "Skizofrenia adalah gangguan mental yang menyebabkan persepsi dan pemikiran yang terdistorsi.",
    "Gangguan kecemasan adalah kondisi di mana seseorang mengalami kecemasan yang berlebihan dan tidak terkendali.",
    "Frustrasi adalah perasaan ketidakpuasan karena kegagalan mencapai tujuan.",
    "Psikopat adalah individu yang memiliki kurangnya empati dan rasa bersalah serta cenderung melakukan perilaku antisosial.",
    "Efek Pygmalion adalah prediksi bahwa keyakinan seseorang terhadap kemampuan orang lain mempengaruhi kinerja mereka.",
    "Kompleks Oedipus adalah konsep dalam psikoanalisis di mana anak laki-laki mengalami perasaan cemburu terhadap ayah mereka.",
    "Anak-anak yang mengalami masa perceraian orang tua mereka mungkin mengalami kesulitan penyesuaian sosial.",
    "Psikologi klinis adalah cabang psikologi yang berfokus pada diagnosis dan pengobatan gangguan mental.",
    "Efek mereproduksi adalah kecenderungan untuk mengingat informasi yang sesuai dengan kepercayaan atau pandangan kita.",
    "Kepribadian adalah pola perilaku, emosi, dan pikiran yang konsisten dari seseorang.",
    "Efek khusus adalah kecenderungan untuk menganggap diri kita lebih unik daripada orang lain.",
    "Resistensi adalah pertahanan psikologis yang mencegah akses ke pikiran atau perasaan yang menyakitkan.",
    "Mekanisme pertahanan adalah strategi mental untuk mengurangi kecemasan dan menghadapi konflik.",
    "Histeria adalah gangguan psikologis yang menyebabkan gejala fisik tanpa penyebab fisik yang jelas.",
    "Penyimpangan sosial adalah perilaku yang menyimpang dari norma sosial yang berlaku.",
    "Pemusatan diri adalah kecenderungan untuk fokus pada aspek diri yang positif dan mengabaikan aspek negatif.",
    "Efek primasi adalah kecenderungan untuk mengingat informasi yang disajikan lebih awal dengan lebih baik.",
    "Psikologi pendidikan mempelajari proses pembelajaran dan pengajaran serta pengembangan kognitif.",
    "Gangguan bipolar adalah gangguan mood yang menyebabkan perubahan antara depresi dan mania.",
    "Teori perkembangan moral oleh Lawrence Kohlberg mengidentifikasi enam tingkatan moralitas.",
    "Psikologi evolusi mempelajari bagaimana perilaku manusia berkembang untuk meningkatkan kesempatan reproduksi.",
    "Gangguan obsesif-kompulsif adalah kondisi di mana seseorang memiliki pikiran obsesif yang mengganggu dan tindakan kompulsif.",
    "Psikologi olahraga mempelajari faktor-faktor psikologis yang mempengaruhi kinerja atlet.",
    "Gangguan kepribadian adalah pola perilaku yang menetap dan tidak sesuai dengan norma sosial.",
    "Penyesuaian sosial adalah kemampuan seseorang untuk berinteraksi dengan orang lain secara efektif.",
    "Psikologi industri dan organisasi mempelajari perilaku individu dan kelompok di tempat kerja.",
    "Fobia adalah ketakutan yang berlebihan terhadap objek atau situasi tertentu.",
    "Kecanduan adalah keadaan di mana seseorang tidak dapat mengontrol penggunaan substansi atau perilaku tertentu.",
    "Introspeksi adalah pengamatan dan analisis diri terhadap pikiran dan perasaan.",
    "Percobaan Stanford adalah studi yang menguji efek psikologis dari peran tahanan dan penjaga.",
    "Efek placebo adalah perbaikan kondisi kesehatan seseorang karena keyakinan bahwa mereka menerima pengobatan yang efektif.",
    "Disonansi kognitif adalah ketidaksesuaian antara keyakinan atau nilai-nilai seseorang dengan perilaku mereka.",
    "Psikologi forensik mempelajari interaksi antara psikologi dan sistem hukum.",
    "Keputusan irasional adalah keputusan yang dibuat berdasarkan emosi dan intuisi daripada pemikiran logis.",
    "Psikologi lingkungan mempelajari bagaimana lingkungan fisik mempengaruhi kesehatan dan perilaku manusia.",
    "Hipnosis adalah keadaan kesadaran yang menginduksi perubahan dalam kesadaran dan respons seseorang.",
    "Mimpi adalah pengalaman bawah sadar yang melibatkan gambar, emosi, dan sensasi.",
  ],
  astronomi: [
    "Astronomi adalah ilmu yang mempelajari benda-benda langit di alam semesta.",
    "Bumi adalah planet ketiga dari matahari dalam tata surya kita.",
    "Matahari adalah bintang pusat tata surya kita.",
    "Bulan adalah satelit alami Bumi.",
    "Tata surya terdiri dari delapan planet: Merkurius, Venus, Bumi, Mars, Jupiter, Saturnus, Uranus, dan Neptunus.",
    "Planet terbesar dalam tata surya adalah Jupiter.",
    "Planet terkecil dalam tata surya adalah Merkurius.",
    "Bintang adalah bola gas panas yang menghasilkan cahaya dan energi melalui reaksi nuklir.",
    "Bintang terdekat dari Bumi adalah Matahari.",
    "Bima Sakti adalah galaksi tempat Bumi berada.",
    "Bima Sakti merupakan galaksi spiral.",
    "Bima Sakti memiliki diameter sekitar 100.000 tahun cahaya.",
    "Galaksi Andromeda adalah tetangga terdekat dari Bima Sakti.",
    "Terdapat miliaran galaksi di alam semesta.",
    "Lubang hitam adalah area di alam semesta dengan gaya gravitasi sangat kuat sehingga tidak ada apa pun yang dapat lolos darinya, termasuk cahaya.",
    "Bukti awal tentang teori Big Bang menunjukkan bahwa alam semesta berasal dari ledakan besar sekitar 13,8 miliar tahun lalu.",
    "Hubble Space Telescope adalah teleskop luar angkasa yang mengorbit Bumi dan memberikan gambar-gambar luar angkasa berkualitas tinggi.",
    "Cepheid variables adalah bintang yang mengalami variasi periodik dalam kecerahannya dan digunakan untuk mengukur jarak ke galaksi jauh.",
    "Teori relativitas umum oleh Albert Einstein menjelaskan gravitasi sebagai kelengkungan ruang-waktu.",
    "Bukti gravitasi gelombang pertama kali diamati oleh LIGO (Laser Interferometer Gravitational-Wave Observatory) pada tahun 2015.",
    "Fenomena cincin cahaya yang terlihat selama gerhana matahari total disebut sebagai cincin api.",
    "Gerhana bulan terjadi ketika Bumi berada di antara matahari dan bulan, menghalangi cahaya matahari yang mencapai permukaan bulan.",
    "Gerhana matahari terjadi ketika bulan berada di antara matahari dan Bumi, menyebabkan bayangan bulan jatuh ke permukaan Bumi.",
    "Satelit alami Saturnus, Enceladus, memiliki samudra bawah permukaan es yang mungkin berpotensi menyimpan kehidupan.",
    "Proxima Centauri adalah bintang terdekat setelah Matahari.",
    "Skala waktu alam semesta diukur dalam miliaran tahun.",
    "Awan Oort adalah wilayah di luar tata surya yang berisi berjuta-juta objek beku, termasuk komet dan planetesimal.",
    "Teleskop radio digunakan untuk mengamati gelombang radio yang dipancarkan oleh objek langit.",
    "Fenomena aurora di Bumi disebabkan oleh partikel bermuatan yang bertabrakan dengan atmosfer di dekat kutub.",
    "Misi Voyager adalah misi eksplorasi luar angkasa yang telah mengunjungi Jupiter, Saturnus, Uranus, dan Neptunus.",
    "Teleskop James Webb adalah teleskop luar angkasa berikutnya yang diharapkan dapat memberikan gambar luar angkasa dengan resolusi lebih tinggi dari sebelumnya.",
    "Salah satu teori tentang akhir alam semesta adalah Big Freeze, di mana alam semesta akan terus berkembang hingga mati kedinginan.",
    "Salah satu teori tentang akhir alam semesta adalah Big Crunch, di mana gravitasi akan menghentikan ekspansi alam semesta dan mengarah pada kontraksi kembali.",
    "Salah satu teori tentang akhir alam semesta adalah Big Rip, di mana daya tarik gelap akan merobek semua struktur di alam semesta.",
    "Nebula adalah awan gas dan debu antarbintang yang merupakan tempat kelahiran bintang.",
    "Katai coklat adalah objek langit yang lebih besar dari planet, tetapi lebih kecil dari bintang dan tidak memiliki reaksi nuklir.",
    "Katai putih adalah bintang tua yang padat yang tersisa setelah bintang merah raksasa melepaskan lapisan luar.",
    "Nova adalah kilatan cahaya yang tiba-tiba dari bintang yang mengalami ledakan nuklir di permukaannya.",
    "Supernova adalah ledakan besar yang terjadi ketika bintang sangat masif meledak pada akhir siklus hidupnya.",
    "Asteroid adalah benda langit kecil yang mengorbit matahari, sebagian besar terletak di antara orbit Mars dan Jupiter di sabuk asteroid.",
    "Komet adalah benda langit yang terdiri dari es, debu, dan gas yang mengorbit matahari dengan orbit eksentrik.",
    "Hubble Deep Field adalah gambar luar angkasa yang menunjukkan ribuan galaksi sangat jauh di alam semesta.",
    "Zona laik huni adalah wilayah di sekitar bintang di mana planet dengan kondisi yang memungkinkan kehidupan dapat eksis.",
    "Teori panspermia adalah gagasan bahwa kehidupan di Bumi berasal dari materi yang dibawa oleh komet atau asteroid dari luar angkasa.",
    "Pergeseran merah adalah pergeseran frekuensi cahaya dari objek jauh ke ujung merah spektrum, mengindikasikan bahwa objek tersebut menjauh dari kita.",
    "Pergeseran biru adalah pergeseran frekuensi cahaya dari objek jauh ke ujung biru spektrum, mengindikasikan bahwa objek tersebut mendekati kita.",
    "Aurora Borealis adalah fenomena cahaya yang terjadi di belahan utara Bumi, juga dikenal sebagai Northern Lights.",
    "Aurora Australis adalah fenomena cahaya yang terjadi di belahan selatan Bumi, juga dikenal sebagai Southern Lights.",
    "Gerhana matahari cincin terjadi ketika bulan menutupi bagian tengah matahari, meninggalkan cincin cahaya matahari di sekitarnya.",
    "Tiang cahaya adalah efek optik yang menyebabkan cahaya matahari dipantulkan oleh kristal es di udara.",
    "Fenomena mirip pelangi di malam hari disebut halo dan disebabkan oleh pembiasan cahaya matahari oleh kristal es.",
    "Asteroid yang cukup besar dan berpotensi berbahaya bagi Bumi disebut sebagai asteroid potensial mematikan.",
    "Jalur hijau adalah daerah di langit malam di mana pengamat dapat melihat pemandangan langit yang sangat gelap dan bebas dari cahaya polusi.",
    "Teleskop reflektor adalah jenis teleskop yang menggunakan cermin untuk memantulkan dan mengumpulkan cahaya dari objek langit.",
  ],
  // there will be more soon!!    
  };
  
  module.exports = {
    knowledgeBase,
  };
  