const quotes = {
    "asmaraloka": [
      "Cinta sejati tidak akan pernah berakhir.",
      "Jatuh cinta adalah seperti merasakan keajaiban setiap hari.",
      "Cinta adalah bahasa yang bisa dimengerti oleh hati.",
      "Semesta memaksaku melepaskanmu,\ntapi semesta pula yang selalu punya cara untuk mengingatkan ku padamu.",
      "Patah hati terberat adalah ketika kita memohon\nkepada Tuhan  bukan untuk menyatukan melainkan untuk melupakan",
      "Mencintai mu memanglah candu\nTapi memiliki mu hanya cerita fiksi yg lucu",
      "Ekspektasi hanya mengundang harapan yang besar, dan realita mendatangkan kekecewaan yang setimpal",
      "Bercanda mu terlalu membawa rasa sehingga aku lupa bahwa kita hanya sekedar dua manusia yang berbeda rasa",
      "Bukan dia yang sepenuhnya mengecewakan, tetapi ekspetasi kita yang berlebihan",
      "Dia kini hanyalah angan, seperti bayangan yang perlahan hilang ditelan kegelapan",
      "Yang Buruk Sengaja Allah Lepaskan, Agar Yang Baik Mempunyai Kesempatan Untuk Datang",
      "Jangan pernah membuat patah hati seorang penulis, atau kau akan abadi dalam karyanya",
      "Aku telah melupakan langit dan memilihmu sebagai laut,\nuntukmu aku berenang,\ndemi mu aku rela menyelam\ndan karnamu pula aku tenggelam.",
      "Dibalik harapan, ada pengorbanan. Dibalik kepastian, ada penantian",
      "rapapa semisal sek dinanti ra kunjung menepi, nko yo diganti karo seng lueh gemati",
      "sekedar dekat tanpa ikatan, sekedar teman namun takut kehilangan",
      "Bangkit dari sebuah kehancuran,dan hancur lagi karena sebuah harapan",
      "Sebuah epilog tanpa prolog, kisah yang tak pernah dimulai namun berakhir tanpa kata selesai",
      "Kukira cuekmu menguji, ternyata menyuruhku pergi",
      "berawal dari rasa suka, dan berakhir dalam lautan luka",
      "Dulu rasamu seperti hujan deras. Lalu aku ingat sederas-derasnya hujan ia akan tetap reda",
      "Emang boleh ya secantik itu?",
      "Sesopan apapun kamu pergi, yang namanya pamitan tetaplah menyakitkan",
      "Bisa gak, kita ngobrol balik kaya pas baru kenalan?",
      "ok, makasih untuk lukanya",
      "pengen rasanya ngancurin duina",
      "Semoga kelak kita dapat menyaksikan matahari terbit dari jendela yang sama ",
      "Menaruh harapan pada manusia, adalah seni paling sederhana untuk menderita",
      "Terlalu mencintai ciptaan-Nya, tuhanpun cemburu lalu membirimu luka",
      "Tahu tempe is good, but tahu diri is better :)",
      "Cuman senja yang bisa pergi dengan indah",
      "Emang harus dia?",
      "Enggak harus dia kok",
      "Maaf, aku lupa aku bukan siapa siapa",
      "Goblok lu bang, dia aja baik-baik aja tanpa kabar dari lu, sadar lah bang",
      "Kayaknya dia gak butuh lu bang, tuh dia bahagia aja tanpa kabar dari lu",
      "Lu masih betah bang ama dia?",
      "Betah atau terpaksa?",
      "Wkwkwk udah dikecewain berkali-kali aja lu masih gak bisa buka mata",
      "Enggak paham lagi",
      "aku pamit",
      "makasih ya... aku udah gak akan menaruh harapan lagi",
      "ternyata begitu, maaf kalau ku kira kita sama-sama suka"
    ],
    "motivasi": [
        "kegagalan adalah ibarat tanda koma, dia membuat jeda namun tak membuat henti",
        "Tidak semua ekspetasi itu nyata, namun kita harus lebih bisa menerima realitanya",
        "Hidup gak akan bertambah mudah, kamu lah yang seharusnya bertambah kuat",
        "Semangat yaa!\niya semalam nangis berat",
        "Jika kamu tidak pernah bertanya, maka jawabannya akan selalu tidak",
        "Mengapa tidak? hidup cuma sekali",
        "Kemarin aja kamu bilangnya besok, jadi mau dimulai kapan?",
        "Percaya gak, sama rencanaku? -semesta",
        "Kegagalan yang sebenarnya adalah tidak pernah mencoba sama sekali",
        "1 Tahun = 365 Kesempatan",
        "Apa yang akan kamu lakukan, jika kamu gak takut?",
        "Kesuksesan dimulai dari niat dan kerja keras.",
        "Jangan pernah menyerah, karena setiap kegagalan adalah pelajaran.",
        "Keyakinan diri adalah kunci menuju kesuksesan.",
        "Impian besar memerlukan langkah-langkah kecil untuk mencapainya.",
        "Hidup hanya sekali, jadikan setiap momen berarti.",
        "Ketika kamu merasa lelah, ingatlah mengapa kamu memulai.",
        "Berani menghadapi tantangan adalah ciri-ciri orang kuat.",
        "Kegagalan bukan akhir dari segalanya, tetapi awal dari perbaikan.",
        "Kesuksesan adalah hasil dari kesabaran dan ketekunan.",
        "Kesempatan hanya datang kepada mereka yang mau menciptakannya.",
        "Jangan pernah menunda-nunda, lakukan sekarang juga.",
        "Hidup adalah petualangan, nikmati setiap langkahnya.",
        "Belajar dari masa lalu, tetapi fokuslah pada masa depan.",
        "Hargai dirimu sendiri, karena kamu berharga.",
        "Rencanakan tujuanmu dan tetaplah berjalan ke arahnya.",
        "Jika kamu ingin meraih hal yang belum pernah kamu miliki, kamu harus berani melakukan hal yang belum pernah kamu lakukan.",
        "Jangan takut gagal, karena kegagalan adalah bagian dari proses menuju kesuksesan.",
        "Kamu adalah penulis dari kisah hidupmu sendiri.",
        "Hargai waktu, karena waktu adalah hal terberharga yang tidak bisa kembali.",
        "Ketika kamu berpikir kamu tidak mampu, ingatlah semua alasan mengapa kamu bisa.",
        "Kamu bisa, jika kamu percaya bahwa kamu bisa.",
        "Jangan biarkan ketakutan menghalangi langkahmu menuju impianmu.",
        "Setiap kesulitan pasti memiliki akhir yang manis.",
        "Jangan biarkan orang lain menentukan siapa kamu, tetapi tunjukkan siapa kamu sebenarnya.",
        "Kesuksesan adalah tentang persiapan bertemu dengan kesempatan."
    ],
    "filosofi": [
      "Hidup adalah perjalanan menuju pemahaman diri dan makna hidup.",
      "Tiada kebahagiaan tanpa pemahaman akan penderitaan.",
      "Kesadaran adalah kunci untuk membebaskan diri dari belenggu pikiran.",
      "Hidup adalah perjalanan, bukan tujuan akhir.",
      "Ketidakpastian adalah satu-satunya hal yang pasti dalam hidup.",
      "Keberanian adalah ketika kamu menghadapi ketakutanmu.",
      "Kebahagiaan bukanlah tujuan, melainkan cara hidup.",
      "Penting untuk merenung dan menemukan makna di balik segala hal.",
      "Kehidupan adalah lukisan besar yang sedang kita warnai.",
      "Pertanyaan yang tak berujung adalah bagian dari eksistensi manusia.",
      "Dalam setiap hal sederhana terkandung keindahan yang tak terhingga.",
      "Hidup adalah seperti menari di atas tali tipis.",
      "Kebenaran adalah pencerahan dalam kegelapan.",
      "Sifat kehidupan adalah berubah, dan perubahan adalah konstan.",
      "Pengalaman adalah guru terbaik dalam perjalanan hidup.",
      "Ketidaktahuan adalah permulaan dari kebijaksanaan.",
      "Dalam kesendirian, kita menemukan refleksi diri yang paling dalam.",
      "Makna hidup adalah apa yang kita berikan padanya.",
      "Setiap pertemuan adalah nasib yang telah dituliskan.",
      "Bumi adalah rumah bersama, mari kita jaga bersama.",
      "Keberagaman adalah harta terbesar dalam kehidupan.",
      "Saat air mengalir, ia membawa makna tentang kehidupan.",
      "Dalam kesendirian, kita menemukan kedamaian.",
      "Hidup adalah pergulatan antara cahaya dan kegelapan.",
      "Penerimaan adalah kunci untuk mengatasi penderitaan.",
      "Cinta adalah kekuatan yang paling murni dalam hidup.",
      "Ketika keheningan hadir, kita menemukan inspirasi sejati.",
      "Kebebasan adalah hak setiap manusia untuk mengejar impian mereka.",
      "Kebijaksanaan adalah ketenangan dalam kekacauan."
    ],
    "inspirasi": [
      "Impian adalah bintang pemandu menuju kesuksesan.",
      "Percayalah pada dirimu sendiri, kamu bisa melakukan apapun.",
      "Bersyukurlah atas semua keberhasilan dan kegagalan, keduanya mengajarkan banyak hal.",
      "Hiduplah seperti hari ini adalah hari terakhir dalam hidupmu.",
      "Jangan takut gagal, tetapi takutlah jika kamu tidak mencoba.",
      "Setiap tantangan adalah peluang untuk tumbuh dan berkembang.",
      "Kegagalan adalah batu loncatan menuju kesuksesan.",
      "Yang paling berharga adalah waktu, gunakanlah dengan bijak.",
      "Jangan menunggu kesempurnaan, tetapi mulailah dari mana pun kamu berada.",
      "Kamu adalah pencipta dari hidupmu sendiri, buatlah indah.",
      "Kesempatan jarang datang dua kali, manfaatkanlah dengan sebaik mungkin.",
      "Berani bermimpi besar dan kerjakan rencanamu dengan gigih.",
      "Ketika kamu berhenti belajar, kamu berhenti berkembang.",
      "Tetaplah rendah hati meskipun telah mencapai kesuksesan.",
      "Jangan takut mengambil risiko, karena tanpa risiko tidak ada hasil besar.",
      "Kebahagiaan bukanlah tujuan, melainkan perjalanan hidup.",
      "Setiap hari adalah kesempatan untuk memulai sesuatu yang baru.",
      "Pikirkan positif, dan hal positif akan datang pada dirimu.",
      "Jadilah seseorang yang menginspirasi dan memberikan manfaat bagi orang lain.",
      "Percayalah pada dirimu sendiri, karena kamu mampu meraih impianmu.",
      "Jangan biarkan kegagalan menghentikan langkahmu menuju sukses.",
      "Jadilah orang yang memberi, bukan hanya yang menerima.",
      "Percayalah bahwa setiap hal terjadi dengan alasan yang baik.",
      "Hargai waktu orang lain, karena waktu adalah hal berharga.",
      "Kerja keras adalah kunci untuk mencapai impianmu.",
      "Jangan takut berbicara dan mengungkapkan pendapatmu.",
      "Jadilah pembelajar sepanjang hayat, dan terus berkembang.",
      "Berani mencoba hal baru, karena di situlah kamu bisa menemukan bakatmu.",
      "Jangan pernah menyerah, karena keberhasilan adalah pemberontakan terhadap kegagalan.",
      "Jadilah pemimpin yang menginspirasi dan membimbing orang lain.",
      "Percayalah bahwa kamu berharga dan memiliki potensi yang luar biasa.",
      "Jangan takut untuk berbeda, karena perbedaan adalah keunikanmu.",
      "Ingatlah bahwa setiap hari adalah kesempatan untuk menjadi lebih baik."
    ],
      "humor": [
        "Jangan mengganggu saya saat saya tidur, saya sudah sangat sibuk.",
        "Berhenti merasa tua, itu tidak akan membuatmu menjadi lebih muda.",
        "Aku tidak malas, aku hanya menyimpan energi untuk hal-hal yang lebih penting.",
        "Kalau hidup ini hanya soal makan dan tidur, aku adalah ahli di bidang tersebut.",
        "Jangan pernah berhenti bermimpi, kecuali saat kamu sedang mengemudi.",
        "Ketika hidup memberimu limun, buatlah limunade.",
        "Ketika orang lain panik, kamu santai saja, ada apa hari ini?",
        "Jangan khawatir tentang menu makan malam, makananmu akan datang dalam hitungan menit.",
        "Ketika kamu merasa bodoh, ingatlah bahwa ada orang yang mencoba mengganti baterai TV dengan remote.",
        "Jangan mencoba menjadi seseorang yang tidak kamu sukai, kamu cukup menipu dirimu sendiri saja.",
        "Hidup ini singkat, senyumlah saat kamu masih punya gigi.",
        "Jika kamu merasa pintar, coba jawab pertanyaan anak-anak.",
        "Ketika hidup memberimu jeruk, coba minta garam dan tequila.",
        "Jangan bingung tentang hidup, hidup saja yang akan membingungkanmu.",
        "Hidup itu seperti toilet, kadang kamu harus menurunkan beberapa hal yang tidak berguna.",
        "Jangan menganggap dirimu serius, tidak ada yang menganggapmu serius.",
        "Jangan pernah berhenti tertawa, bahkan ketika situasi tidak lucu.",
        "Hidup itu seperti sepeda, kalau tidak maju, kamu akan terjatuh.",
        "Jangan menangis karena ujian, kembalikan ujian tersebut dengan nilai bagus.",
        "Bekerja keras itu baik, tapi tidur juga penting, jadi tidurlah dengan keras.",
        "Sebagai seorang jenius, aku lebih suka menghabiskan waktuku dengan tidak melakukan apa-apa.",
        "Jangan pernah mengambil kehidupan terlalu serius, kamu tidak akan pernah keluar hidup-hidup.",
        "Ketika orang lain berbicara dengan hewan peliharaan mereka, aku mengerti bahwa ini adalah cinta sejati.",
        "Bekerja keras adalah kuncinya, tetapi berpura-pura bekerja lebih baik.",
        "Jangan takut akan kesalahan, karena itu adalah kesempatan untuk belajar hal baru.",
        "Jadilah lucu atau hilangkan dirimu dari hidup ini.",
        "Jangan takut menjadi dirimu sendiri, jangan biarkan orang lain yang mengisi pakaianmu.",
        "Ketika hidup memberimu jeruk, kamu harus berpikir apakah kamu benar-benar ingin jeruk itu.",
        "Jadilah seperti kopi, kuat, penuh semangat, dan selalu diinginkan.",
        "Jika kamu merasa tidak berguna, ingatlah bahwa kamu masih bisa menjadi contoh buruk.",
        "Jangan mengambil hidup terlalu serius, kamu tidak akan keluar hidup-hidup.",
        "Demi apa? demikian",
      ],
  };
  
  module.exports = quotes;

